import type { LucideIcon } from 'lucide-react'
import {
  ShoppingCart, ChefHat, Settings, Package, Gift, Users, Shield,
  DollarSign, User, LayoutDashboard, Menu, FileIcon, Table2, UtensilsCrossed,
  ClipboardList, UserCog, Store, LogOut, ArrowLeft, ArrowRight, Plus, Minus,
  X, Search, Check, AlertCircle, CreditCard, Smartphone, Receipt,
  FolderTree, EyeOff, Sun, Moon, Home, Bell, Clock, Printer, Truck,
  Download, FileText, Calendar, RefreshCw, Archive, Tag, BarChart, Star,
  MapPin, Phone, Monitor, BookOpen, Settings2, List, Grid3X3, Filter,
  Trash2, Edit, Save, Image, Upload, Link,
} from 'lucide-react'

const iconRegistry: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  'chef-hat': ChefHat,
  'settings': Settings,
  'settings-2': Settings2,
  'package': Package,
  'gift': Gift,
  'users': Users,
  'shield': Shield,
  'dollar-sign': DollarSign,
  'user': User,
  'layout-dashboard': LayoutDashboard,
  'menu': Menu,
  'table': Table2,
  'utensils': UtensilsCrossed,
  'clipboard': ClipboardList,
  'user-cog': UserCog,
  'store': Store,
  'logout': LogOut,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'folder-tree': FolderTree,
  'eye-off': EyeOff,
  'sun': Sun,
  'moon': Moon,
  'home': Home,
  'bell': Bell,
  'clock': Clock,
  'credit-card': CreditCard,
  'smartphone': Smartphone,
  'receipt': Receipt,
  'search': Search,
  'plus': Plus,
  'minus': Minus,
  'x': X,
  'check': Check,
  'alert': AlertCircle,
  'printer': Printer,
  'truck': Truck,
  'download': Download,
  'file-text': FileText,
  'calendar': Calendar,
  'refresh': RefreshCw,
  'archive': Archive,
  'tag': Tag,
  'bar-chart': BarChart,
  'star': Star,
  'map-pin': MapPin,
  'phone': Phone,
  'monitor': Monitor,
  'book-open': BookOpen,
  'list': List,
  'grid': Grid3X3,
  'filter': Filter,
  'trash': Trash2,
  'edit': Edit,
  'save': Save,
  'image': Image,
  'upload': Upload,
  'link': Link,
}

const labelMap: Record<string, string> = {
  'shopping-cart': 'POS / Ventas',
  'chef-hat': 'Cocina',
  'settings': 'Configuración',
  'settings-2': 'Ajustes',
  'package': 'Productos',
  'gift': 'Combos',
  'users': 'Usuarios',
  'shield': 'Roles / Seguridad',
  'dollar-sign': 'Caja / Efectivo',
  'user': 'Cliente',
  'layout-dashboard': 'Dashboard',
  'menu': 'Menú / Navegación',
  'table': 'Mesas',
  'utensils': 'Comedor / Restaurante',
  'clipboard': 'Órdenes / Pedidos',
  'user-cog': 'Administrador',
  'store': 'Tienda / Local',
  'logout': 'Salir',
  'arrow-left': 'Flecha izquierda',
  'arrow-right': 'Flecha derecha',
  'folder-tree': 'Categorías',
  'eye-off': 'Oculto',
  'sun': 'Modo claro',
  'moon': 'Modo oscuro',
  'home': 'Inicio',
  'bell': 'Notificaciones',
  'clock': 'Historial / Tiempo',
  'credit-card': 'Pago tarjeta',
  'smartphone': 'Delivery / Móvil',
  'receipt': 'Facturación',
  'search': 'Buscar',
  'plus': 'Agregar',
  'minus': 'Quitar',
  'x': 'Cerrar / Eliminar',
  'check': 'Confirmar',
  'alert': 'Alerta / Advertencia',
  'printer': 'Imprimir',
  'truck': 'Delivery / Envío',
  'download': 'Descargar',
  'file-text': 'Reporte / Documento',
  'calendar': 'Calendario / Fechas',
  'refresh': 'Actualizar / Sincronizar',
  'archive': 'Archivo',
  'tag': 'Etiqueta / Promoción',
  'bar-chart': 'Reportes / Estadísticas',
  'star': 'Favorito / Destacado',
  'map-pin': 'Ubicación / Dirección',
  'phone': 'Teléfono / Contacto',
  'monitor': 'Pantalla / Visualización',
  'book-open': 'Manual / Guía',
  'list': 'Lista / Detalle',
  'grid': 'Cuadrícula',
  'filter': 'Filtrar',
  'trash': 'Papelera / Eliminar',
  'edit': 'Editar',
  'save': 'Guardar',
  'image': 'Imagen / Foto',
  'upload': 'Subir / Importar',
  'link': 'Enlace / Vínculo',
}

export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? FileIcon
}

export function iconLabel(name: string): string {
  return labelMap[name] ?? name
}

export const iconNames = Object.keys(iconRegistry).sort(
  (a, b) => iconLabel(a).localeCompare(iconLabel(b))
)

export const iconOptions = iconNames.map((name) => ({
  value: name,
  label: iconLabel(name),
}))
